#!/usr/bin/env python3
"""
⚠️  DEPRECATED - Use generate_splits.sh instead
===================================================

This script is kept for reference only.
For current dataset generation, use:
    bash scripts/data_preparation/generate_splits.sh

Current pipeline generates:
- TRAIN: ~700 scenes × 6 cameras = ~4,200 sequences
- VAL:   ~150 scenes × 6 cameras = ~900 sequences  
- TEST:  ~150 scenes × 6 cameras = ~900 sequences

All splits use ALL 6 cameras:
  CAM_FRONT, CAM_FRONT_LEFT, CAM_FRONT_RIGHT,
  CAM_BACK, CAM_BACK_LEFT, CAM_BACK_RIGHT

===================================================

OLD DOCUMENTATION (OBSOLETE):
Script per generare dataset split ottimali per fine-tuning TrackSSM.

Genera 3 split bilanciati:
- TRAIN: 600 scene-cameras (4 camere: FRONT, FRONT_LEFT, FRONT_RIGHT, BACK)
- VAL: 170 scene-cameras (2 camere: FRONT_LEFT, BACK_LEFT)  
- TEST: 80 scene-cameras (2 camere: FRONT_RIGHT, BACK_RIGHT) [HELD OUT]

Ogni split usa camere diverse per evitare overlap e data leakage.

Usage:
    # Step 1: Generate train split
    bash generate_finetuning_splits.sh train
    
    # Step 2: Generate val split
    bash generate_finetuning_splits.sh val
    
    # Step 3: Generate test split
    bash generate_finetuning_splits.sh test
"""

import argparse
from pathlib import Path

# Configurazione split
SPLIT_CONFIG = {
    "train": {
        "nuscenes_split": "train",
        "cameras": ["CAM_FRONT", "CAM_FRONT_LEFT", "CAM_FRONT_RIGHT", "CAM_BACK"],
        "expected_sequences": 600,
        "description": "Main training split with 4 diverse cameras"
    },
    "val": {
        "nuscenes_split": "val",
        "cameras": ["CAM_FRONT_LEFT", "CAM_BACK_LEFT"],
        "expected_sequences": 170,
        "description": "Validation split with 2 left-side cameras"
    },
    "test": {
        "nuscenes_split": "val",
        "cameras": ["CAM_FRONT_RIGHT", "CAM_BACK_RIGHT"],
        "expected_sequences": 80,
        "description": "Test split with 2 right-side cameras (HELD OUT)"
    }
}

def generate_command(split_name, nusc_root, out_root):
    """Genera comando bash per eseguire prepare_nuscenes_interpolated.py"""
    
    config = SPLIT_CONFIG[split_name]
    
    cameras_str = " ".join(config["cameras"])
    
    command = f"""
# ============================================================================
# Fine-tuning split: {split_name.upper()}
# {config["description"]}
# Expected sequences: ~{config["expected_sequences"]}
# ============================================================================

python prepare_nuscenes_interpolated.py \\
    --nusc_root {nusc_root} \\
    --version v1.0-trainval \\
    --out_root {out_root} \\
    --split {config["nuscenes_split"]} \\
    --cameras {cameras_str} \\
    --interpolate \\
    --min_vis 2

echo ""
echo "✓ {split_name.upper()} split generated"
echo ""
"""
    
    return command


def main():
    parser = argparse.ArgumentParser(description="Generate fine-tuning dataset commands")
    parser.add_argument(
        "--nusc_root",
        default="/mnt/datasets/Nuscense",
        help="Path to NuScenes root"
    )
    parser.add_argument(
        "--out_root",
        default="./data/nuscenes_finetuning_interpolated",
        help="Output directory for fine-tuning dataset"
    )
    parser.add_argument(
        "--output_script",
        default="./scripts/generate_finetuning_splits.sh",
        help="Path to output bash script"
    )
    
    args = parser.parse_args()
    
    # Crea bash script completo
    script_content = f"""#!/bin/bash
# Auto-generated script for TrackSSM fine-tuning dataset preparation
# Generated by: prepare_finetuning_splits.py
#
# This script generates 3 dataset splits with temporal interpolation (2Hz → 12fps):
#   - TRAIN: 600 scene-cameras (4 cameras)
#   - VAL: 170 scene-cameras (2 cameras)
#   - TEST: 80 scene-cameras (2 cameras, held out)
#
# Usage:
#   bash {args.output_script} [train|val|test|all]

set -e

NUSC_ROOT="{args.nusc_root}"
OUT_ROOT="{args.out_root}"

# Check arguments
if [ $# -eq 0 ]; then
    echo "Usage: $0 [train|val|test|all]"
    exit 1
fi

SPLIT=$1

case $SPLIT in
    train)
{generate_command("train", args.nusc_root, args.out_root)}
        ;;
    
    val)
{generate_command("val", args.nusc_root, args.out_root)}
        ;;
    
    test)
{generate_command("test", args.nusc_root, args.out_root)}
        ;;
    
    all)
        echo "Generating ALL splits (train, val, test)..."
        echo ""
{generate_command("train", args.nusc_root, args.out_root)}
{generate_command("val", args.nusc_root, args.out_root)}
{generate_command("test", args.nusc_root, args.out_root)}
        
        echo "============================================================================"
        echo "ALL SPLITS GENERATED"
        echo "============================================================================"
        echo ""
        echo "Dataset structure:"
        echo "  {args.out_root}/"
        echo "    train/    (~600 scene-cameras, 4 cameras)"
        echo "    val/      (~170 scene-cameras, 2 cameras)"
        echo "    val/      (~80 scene-cameras, 2 cameras, TEST HELD OUT)"
        echo ""
        echo "Camera distribution:"
        echo "  TRAIN: FRONT, FRONT_LEFT, FRONT_RIGHT, BACK"
        echo "  VAL:   FRONT_LEFT, BACK_LEFT"
        echo "  TEST:  FRONT_RIGHT, BACK_RIGHT (HELD OUT)"
        echo ""
        echo "Next steps:"
        echo "  1. Verify dataset with: ls -lh {args.out_root}/*/"
        echo "  2. Check sequence counts match expected (~600, ~170, ~80)"
        echo "  3. Start Phase 1 fine-tuning: python train_phase1_decoder.py"
        echo "============================================================================"
        ;;
    
    *)
        echo "Error: Invalid split '$SPLIT'"
        echo "Usage: $0 [train|val|test|all]"
        exit 1
        ;;
esac
"""
    
    # Salva script
    output_path = Path(args.output_script)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write(script_content)
    
    # Rendi eseguibile
    output_path.chmod(0o755)
    
    print(f"\n✓ Bash script generated: {output_path}")
    print(f"\nTo generate dataset splits, run:")
    print(f"  bash {output_path} all         # Generate all splits")
    print(f"  bash {output_path} train       # Generate only train")
    print(f"  bash {output_path} val         # Generate only val")
    print(f"  bash {output_path} test        # Generate only test")
    print(f"\nSplit configuration:")
    for split_name, config in SPLIT_CONFIG.items():
        print(f"\n  {split_name.upper()}:")
        print(f"    NuScenes split: {config['nuscenes_split']}")
        print(f"    Cameras: {', '.join(config['cameras'])}")
        print(f"    Expected: ~{config['expected_sequences']} sequences")
        print(f"    {config['description']}")


if __name__ == "__main__":
    main()
